server:
  port: 2023
spring:
  security:
    user:
      name: admin
      password: 123456
      roles: experimenter
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/pysharkDB
    username: root
    password: root