version: '3'
services:
  php:
    image: php:5.6-apache
    ports:
      - "10080:80"
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "18080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root