version: '3'
services:
  php:
    image: dulljz/xhcms-php:latest
    ports:
      - "1080:80"
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "18080:8080"